# Proxmox configuration
proxmox_token_secret: "{{ vault_proxmox_token_secret.prod }}"
proxmox_host: 192.168.0.124
proxmox_node: pve-h4


# LXC container configuration
lxc_vmid: "{{ id }}"
lxc_hostname: "{{ hostname }}"
lxc_template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
lxc_storage: local-lvm
lxc_memory: 4096
lxc_swap: 2048
lxc_disk: 8
lxc_cores: 2
lxc_bridge: vmbr1
lxc_ip: 10.0.0.{{ id }}/24
lxc_gateway: 10.0.0.1
lxc_network_interface: eth0
lxc_start_on_boot: false


ssh_key_file: ~/.ssh/selfhosted-cloud-ssh.key.pub
dns_server1: 10.0.0.1
dns_server2: 1.1.1.1